 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carrental.views;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import lk.ijse.carrental.IDGenerator.IDGenerator;
import lk.ijse.carrental.controller.ControllerFactory;
import lk.ijse.carrental.controller.custom.CustomerController;
import lk.ijse.carrental.dto.CustomerDTO;

/**
 *
 * @author Nuwan Pradeep
 */
public class addCustomer extends javax.swing.JFrame {
    
    private CustomerController custController;

    /**
     * Creates new form addCustomer
     */
    public addCustomer() {
        initComponents();
        setId();
        
        custController = (CustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER);
        loadCustomerIDs();
    }
    public void setId() {
        try {
            String newId = IDGenerator.getNewId("customer", "CID", "C", 2);
            idTxt.setText(newId);
            idTxt.setEditable(false);
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectCustomerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        vehicleBrandDetailsPanel = new javax.swing.JPanel();
        nameText3 = new javax.swing.JLabel();
        nameText6 = new javax.swing.JLabel();
        nameText7 = new javax.swing.JLabel();
        nameText8 = new javax.swing.JLabel();
        nameText4 = new javax.swing.JLabel();
        nameText9 = new javax.swing.JLabel();
        nameText10 = new javax.swing.JLabel();
        nameText11 = new javax.swing.JLabel();
        nameText12 = new javax.swing.JLabel();
        nameText13 = new javax.swing.JLabel();
        nameText5 = new javax.swing.JLabel();
        nameText14 = new javax.swing.JLabel();
        nameText1 = new javax.swing.JTextField();
        addressText1 = new javax.swing.JTextField();
        custIDComboBox = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        nameText15 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        licenseText = new javax.swing.JTextField();
        NICText = new javax.swing.JTextField();
        DOBText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        tpText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        addCustomerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectCustomerPanel.setBackground(new java.awt.Color(153, 153, 153));
        selectCustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Select Customer  ");
        selectCustomerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 170, -1));

        vehicleBrandDetailsPanel.setBackground(new java.awt.Color(102, 102, 102));
        vehicleBrandDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameText3.setBackground(new java.awt.Color(102, 204, 255));
        nameText3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText3.setText("Full Name :");
        vehicleBrandDetailsPanel.add(nameText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        nameText6.setBackground(new java.awt.Color(102, 204, 255));
        nameText6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText6.setText("Are you register? Please select your ID ");
        vehicleBrandDetailsPanel.add(nameText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        nameText7.setBackground(new java.awt.Color(102, 204, 255));
        nameText7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText7.setText("Customer ID : ");
        vehicleBrandDetailsPanel.add(nameText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        nameText8.setBackground(new java.awt.Color(102, 204, 255));
        nameText8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText8.setText("License no. : ");
        vehicleBrandDetailsPanel.add(nameText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        nameText4.setBackground(new java.awt.Color(102, 204, 255));
        nameText4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText4.setText("Address :");
        vehicleBrandDetailsPanel.add(nameText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        nameText9.setBackground(new java.awt.Color(102, 204, 255));
        nameText9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText9.setText("Email : ");
        vehicleBrandDetailsPanel.add(nameText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        nameText10.setBackground(new java.awt.Color(102, 204, 255));
        nameText10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText10.setText("Tp No. :");
        vehicleBrandDetailsPanel.add(nameText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        nameText11.setBackground(new java.awt.Color(102, 204, 255));
        nameText11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText11.setText("Date of Birth :");
        vehicleBrandDetailsPanel.add(nameText11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        nameText12.setBackground(new java.awt.Color(102, 204, 255));
        nameText12.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText12.setText("NIC No. : ");
        vehicleBrandDetailsPanel.add(nameText12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        nameText13.setBackground(new java.awt.Color(102, 204, 255));
        nameText13.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText13.setText("Customer ID : ");
        vehicleBrandDetailsPanel.add(nameText13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        nameText5.setBackground(new java.awt.Color(102, 204, 255));
        nameText5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText5.setText("Full Name :");
        vehicleBrandDetailsPanel.add(nameText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        nameText14.setBackground(new java.awt.Color(102, 204, 255));
        nameText14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText14.setText("Address :");
        vehicleBrandDetailsPanel.add(nameText14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));
        vehicleBrandDetailsPanel.add(nameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 290, -1));
        vehicleBrandDetailsPanel.add(addressText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 290, -1));

        vehicleBrandDetailsPanel.add(custIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 290, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        vehicleBrandDetailsPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 10, 460));

        nameText15.setBackground(new java.awt.Color(102, 204, 255));
        nameText15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText15.setText("Are you not registered.. Please fill you information ");
        vehicleBrandDetailsPanel.add(nameText15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        idTxt.setName(""); // NOI18N
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        vehicleBrandDetailsPanel.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 290, -1));

        nameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextMouseClicked(evt);
            }
        });
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });
        vehicleBrandDetailsPanel.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 290, -1));

        licenseText.setName(""); // NOI18N
        licenseText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                licenseTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                licenseTextFocusLost(evt);
            }
        });
        licenseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseTextActionPerformed(evt);
            }
        });
        licenseText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                licenseTextKeyReleased(evt);
            }
        });
        vehicleBrandDetailsPanel.add(licenseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 290, -1));

        NICText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICTextActionPerformed(evt);
            }
        });
        NICText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICTextKeyReleased(evt);
            }
        });
        vehicleBrandDetailsPanel.add(NICText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 290, -1));

        DOBText.setName(""); // NOI18N
        DOBText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextFocusLost(evt);
            }
        });
        DOBText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTextActionPerformed(evt);
            }
        });
        vehicleBrandDetailsPanel.add(DOBText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 290, -1));

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        vehicleBrandDetailsPanel.add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 290, -1));

        tpText.setName(""); // NOI18N
        tpText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpTextFocusLost(evt);
            }
        });
        tpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTextActionPerformed(evt);
            }
        });
        tpText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpTextKeyTyped(evt);
            }
        });
        vehicleBrandDetailsPanel.add(tpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 290, -1));

        emailText.setName(""); // NOI18N
        emailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFocusLost(evt);
            }
        });
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        emailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTextKeyTyped(evt);
            }
        });
        vehicleBrandDetailsPanel.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 290, -1));

        selectCustomerPanel.add(vehicleBrandDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1040, 530));

        addCustomerBtn.setBackground(new java.awt.Color(51, 102, 255));
        addCustomerBtn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerBtn.setText("Add");
        addCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtnMouseClicked(evt);
            }
        });
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });
        selectCustomerPanel.add(addCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtnMouseClicked

    }//GEN-LAST:event_addCustomerBtnMouseClicked

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        /*String name = nameText.getText().trim();
        String tel = tpText.getText().trim();
        String email = emailText.getText();
        String nic = NICText.getText();
        String license = licenseText.getText();
        if(1==1){
        if(name.matches("[A-Z. a-z]")){
        if(tel.matches("^\\d{3}\\d{7}$")){
        if(email.matches("^[A-Za-z0-9]+.*[A-Za-z0-9]+@[A-Za-z0-9]+[A-Za-z0-9].+[A-Za-z0-9].$")){
        if(nic.matches("^[0-9]{1,9}[VvXx]$")){
        if(license.matches("^[B][0-9]{1,7}$")){
        
        }else{
        JOptionPane.showMessageDialog(this, "License number is incorrect");
        licenseText.requestFocusInWindow();
        //licenseText.setText("");
        }
        }else{
        JOptionPane.showMessageDialog(this, "NIC number is incorrect");
        NICText.requestFocusInWindow();
        //NICText.setText("");
        }
        }else{
        JOptionPane.showMessageDialog(this, "Email address is incorrect");
        emailText.requestFocusInWindow();
        //emailText.setText("");
        }
        }else{
        JOptionPane.showMessageDialog(this, "Telephone number is incorrect");
        tpText.requestFocusInWindow();
        //tpText.setText("");
        }
        }else{
        JOptionPane.showMessageDialog(this, "Name is incorrect");
        nameText.requestFocusInWindow();
        //nameText.setText("");
        }
        }else{
        
        }*/
        CustomerDTO customer = new CustomerDTO(
            idTxt.getText(),
            nameText.getText(),
            licenseText.getText(),
            NICText.getText(),
            DOBText.getText(),
            addressText.getText(),
            Integer.parseInt(tpText.getText()),
            emailText.getText());
            
        try {
            CustomerDTO customer1 =custController.search(idTxt.getText());
            if(customer1==null){
                try { 
                    boolean result = custController.add(customer);
                    if (result){
                        JOptionPane.showMessageDialog(this, "Customer has been successfully added...");
                    }else{
                        JOptionPane.showMessageDialog(this, "Customer has not been added...");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
                } 
        }else{
            JOptionPane.showMessageDialog(this, "duplicate entry...");
        }
    } catch (Exception ex) {
        Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
            
        
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void licenseTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseTextFocusGained
        licenseText.paint(null);
    }//GEN-LAST:event_licenseTextFocusGained

    private void licenseTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseTextFocusLost

    private void DOBTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextFocusGained

    private void DOBTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextFocusLost

    private void tpTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tpTextFocusGained

    private void tpTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tpTextFocusLost

    private void emailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFocusGained

    private void emailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFocusLost

    private void NICTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICTextActionPerformed
        
    }//GEN-LAST:event_NICTextActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        String name = nameText.getText().trim();
        if(name.matches("[A-Z. a-z]")){
        
        }else{
            JOptionPane.showMessageDialog(this, "Name is incorrect");
            nameText.requestFocusInWindow();   
        }
    }//GEN-LAST:event_nameTextKeyReleased

    private void licenseTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_licenseTextKeyReleased
        String license = licenseText.getText();
        if(license.matches("^[B][0-9]{1,7}$")){

        }else{
            JOptionPane.showMessageDialog(this, "License number is incorrect");
            licenseText.requestFocusInWindow();
                                //licenseText.setText("");
        }             
    }//GEN-LAST:event_licenseTextKeyReleased

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        
        licenseText.requestFocus();
    }//GEN-LAST:event_nameTextActionPerformed

    private void licenseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseTextActionPerformed
        NICText.requestFocus();
    }//GEN-LAST:event_licenseTextActionPerformed

    private void DOBTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTextActionPerformed
        addressText.requestFocus();
    }//GEN-LAST:event_DOBTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        tpText.requestFocus();
    }//GEN-LAST:event_addressTextActionPerformed

    private void tpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTextActionPerformed
        emailText.requestFocus();
    }//GEN-LAST:event_tpTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        addCustomerBtn.requestFocus();
    }//GEN-LAST:event_emailTextActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void tpTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpTextKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||(c == KeyEvent.VK_BACK_SPACE) ||(c == KeyEvent.VK_DELETE)||(c == KeyEvent.VK_ENTER))|tpText.getText().length()>=10) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tpTextKeyTyped

    private void emailTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')||(c >= 'A') && (c <= 'Z') ||(c >= 'a') && (c <= 'z') ||(c =='@')||(c =='.')||(c == KeyEvent.VK_BACK_SPACE) ||(c == KeyEvent.VK_DELETE)||(c == KeyEvent.VK_ENTER))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_emailTextKeyTyped

    private void nameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextMouseClicked
        
    }//GEN-LAST:event_nameTextMouseClicked

    private void NICTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICTextKeyReleased
        String nic = NICText.getText();
        if(nic.matches("^[0-9]{1,9}[VvXx]$")){
                            
        }else{
            JOptionPane.showMessageDialog(this, "NIC number is incorrect");
            NICText.requestFocusInWindow();
            //NICText.setText("");
        }          
    }//GEN-LAST:event_NICTextKeyReleased

    private void tpTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpTextKeyReleased
        String tel = tpText.getText().trim();
        if(tel.matches("^\\d{3}\\d{7}$")){
            DOBText.requestFocus();
        }else{
                JOptionPane.showMessageDialog(this, "Telephone number is incorrect");
                tpText.requestFocusInWindow();
                //tpText.selectAll();
            }   
    }//GEN-LAST:event_tpTextKeyReleased

    private void emailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyReleased
        String email = emailText.getText();
        if(email.matches("^[A-Za-z0-9]+.*[A-Za-z0-9]+@[A-Za-z0-9]+[A-Za-z0-9].+[A-Za-z0-9].$")){
        
        }else{
            JOptionPane.showMessageDialog(this, "Email address is incorrect");
            emailText.requestFocusInWindow();
            //emailText.setText("");
        }  
    }//GEN-LAST:event_emailTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOBText;
    private javax.swing.JTextField NICText;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField addressText1;
    private javax.swing.JComboBox custIDComboBox;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField licenseText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nameText1;
    private javax.swing.JLabel nameText10;
    private javax.swing.JLabel nameText11;
    private javax.swing.JLabel nameText12;
    private javax.swing.JLabel nameText13;
    private javax.swing.JLabel nameText14;
    private javax.swing.JLabel nameText15;
    private javax.swing.JLabel nameText3;
    private javax.swing.JLabel nameText4;
    private javax.swing.JLabel nameText5;
    private javax.swing.JLabel nameText6;
    private javax.swing.JLabel nameText7;
    private javax.swing.JLabel nameText8;
    private javax.swing.JLabel nameText9;
    private javax.swing.JPanel selectCustomerPanel;
    private javax.swing.JTextField tpText;
    private javax.swing.JPanel vehicleBrandDetailsPanel;
    // End of variables declaration//GEN-END:variables
    private void loadCustomerIDs(){
        try{
            ArrayList<CustomerDTO> customerList = custController.getAllIDs();
            for(int i=0;i < customerList.size();i++){
                CustomerDTO customer = customerList.get(i);
                custIDComboBox.addItem(customer.getCID());
            }
        }catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
