/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carrental.views;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.carrental.IDGenerator.IDGenerator;
import lk.ijse.carrental.controller.ControllerFactory;
import lk.ijse.carrental.controller.custom.CustomerController;
import lk.ijse.carrental.controller.custom.VehicleBrandController;
import lk.ijse.carrental.controller.custom.VehicleTypeController;
import lk.ijse.carrental.controller.custom.impl.CustomerControllerImpl;
import lk.ijse.carrental.dao.custom.VehicleTypeDAO;
import lk.ijse.carrental.dto.CustomerDTO;
import lk.ijse.carrental.dto.VehicleBrandDTO;
import lk.ijse.carrental.dto.VehicleTypeDTO;

/**
 *
 * @author Nuwan Pradeep
 */
public class AddVehicle extends javax.swing.JFrame {
    
    private VehicleBrandController ctrlBrand;
    private VehicleTypeController ctrlType;
    private CustomerController cust;
    private static int count;
    /**
     * Creates new form VehicleType
     */
    public AddVehicle() {
        initComponents();
        
        setId();
        
        
        ctrlBrand = (VehicleBrandController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VEHICLEBRAND);
        ctrlType = (VehicleTypeController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VEHICLETYPE);
        cust = (CustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER);
        loadVehicleBrand();
        loadVehicleType();
        //System.out.println(txtid.getText());
    }
    
    
    
    public void setId() {
        try {
            String newId = IDGenerator.getNewId("vehicle_type", "VTID", "VT", 2);
            txtid.setText(newId);
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addressText1 = new javax.swing.JLabel();
        nameText3 = new javax.swing.JLabel();
        salaryText = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtReg = new javax.swing.JTextField();
        salaryText1 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnAddVehicle = new javax.swing.JButton();
        nameText5 = new javax.swing.JLabel();
        btnDeleteVehicle = new javax.swing.JButton();
        btnUpdateVehicle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTypeTable = new javax.swing.JTable();
        salaryText2 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        salaryText3 = new javax.swing.JLabel();
        txtSeat = new javax.swing.JTextField();
        salaryText4 = new javax.swing.JLabel();
        txtFuel = new javax.swing.JTextField();
        salaryText5 = new javax.swing.JLabel();
        salaryText6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtModelName = new javax.swing.JTextField();
        nameText4 = new javax.swing.JLabel();
        vehicleTypeComboBox = new javax.swing.JComboBox();
        txtbrand = new javax.swing.JLabel();
        vehicleBrandComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(153, 153, 153));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Vehicle Information");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 220, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addressText1.setBackground(new java.awt.Color(102, 204, 255));
        addressText1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        addressText1.setForeground(new java.awt.Color(102, 102, 102));
        addressText1.setText("Brand Name :");
        jPanel6.add(addressText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        nameText3.setBackground(new java.awt.Color(102, 204, 255));
        nameText3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText3.setText("New Vehicle Model : ");
        jPanel6.add(nameText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        salaryText.setBackground(new java.awt.Color(102, 204, 255));
        salaryText.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        salaryText.setText("Manufacture Year : ");
        jPanel6.add(salaryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        txtid.setBackground(new java.awt.Color(102, 102, 102));
        txtid.setForeground(new java.awt.Color(153, 255, 255));
        txtid.setBorder(null);
        jPanel6.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, -1));

        txtReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegActionPerformed(evt);
            }
        });
        jPanel6.add(txtReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 250, -1));

        salaryText1.setBackground(new java.awt.Color(102, 204, 255));
        salaryText1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        salaryText1.setText("Reg No. : ");
        jPanel6.add(salaryText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        jPanel6.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 250, -1));

        btnAddVehicle.setBackground(new java.awt.Color(102, 102, 102));
        btnAddVehicle.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAddVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnAddVehicle.setText("Add Vehicle");
        btnAddVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddVehicleMouseClicked(evt);
            }
        });
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });
        jPanel6.add(btnAddVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 180, 20));

        nameText5.setBackground(new java.awt.Color(102, 204, 255));
        nameText5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText5.setText("Vehicle Brand Name :");
        jPanel6.add(nameText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnDeleteVehicle.setBackground(new java.awt.Color(102, 102, 102));
        btnDeleteVehicle.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnDeleteVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteVehicle.setText("Delete Vehicle");
        btnDeleteVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteVehicleMouseClicked(evt);
            }
        });
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });
        jPanel6.add(btnDeleteVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, 20));

        btnUpdateVehicle.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdateVehicle.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnUpdateVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateVehicle.setText("Update Vehicle");
        jPanel6.add(btnUpdateVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, 20));

        vehicleTypeTable.setForeground(new java.awt.Color(102, 0, 102));
        vehicleTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle Model", "Reg No.", "Year", "Color", "Seat Capacity", "Fuel Type", "Price Day", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        vehicleTypeTable.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(vehicleTypeTable);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 970, 180));

        salaryText2.setBackground(new java.awt.Color(102, 204, 255));
        salaryText2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        salaryText2.setText("Vehicle Color : ");
        jPanel6.add(salaryText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        jPanel6.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 250, -1));

        salaryText3.setBackground(new java.awt.Color(102, 204, 255));
        salaryText3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        salaryText3.setText("Seat Capacity : ");
        jPanel6.add(salaryText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        txtSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatActionPerformed(evt);
            }
        });
        jPanel6.add(txtSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 250, -1));

        salaryText4.setBackground(new java.awt.Color(102, 204, 255));
        salaryText4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        salaryText4.setText("Fuel Type : ");
        jPanel6.add(salaryText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        txtFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelActionPerformed(evt);
            }
        });
        jPanel6.add(txtFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 250, -1));

        salaryText5.setBackground(new java.awt.Color(102, 204, 255));
        salaryText5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        salaryText5.setText("Status : ");
        jPanel6.add(salaryText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        salaryText6.setBackground(new java.awt.Color(102, 204, 255));
        salaryText6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        salaryText6.setText("Price per Km : ");
        jPanel6.add(salaryText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel6.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 250, -1));

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        jPanel6.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 250, -1));

        txtModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNameActionPerformed(evt);
            }
        });
        jPanel6.add(txtModelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 250, -1));

        nameText4.setBackground(new java.awt.Color(102, 204, 255));
        nameText4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText4.setText("Vehicle Model : ");
        jPanel6.add(nameText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        vehicleTypeComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        vehicleTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleTypeComboBoxItemStateChanged(evt);
            }
        });
        jPanel6.add(vehicleTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 250, -1));

        txtbrand.setBackground(new java.awt.Color(255, 255, 255));
        txtbrand.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jPanel6.add(txtbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 40, 21));

        vehicleBrandComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        vehicleBrandComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleBrandComboBoxItemStateChanged(evt);
            }
        });
        vehicleBrandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleBrandComboBoxActionPerformed(evt);
            }
        });
        jPanel6.add(vehicleBrandComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 209, -1));

        mainPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1050, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddVehicleMouseClicked
       
    }//GEN-LAST:event_btnAddVehicleMouseClicked

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        VehicleTypeDTO vehicleType = new VehicleTypeDTO(
            txtid.getText(),
            txtbrand.getText(),
            txtModelName.getText(),
            txtReg.getText(),
            Integer.parseInt(txtYear.getText()),
            txtColor.getText(),
            Integer.parseInt(txtSeat.getText()),
            txtFuel.getText(),
            Double.parseDouble(txtPrice.getText()),
            txtStatus.getText());
        try{
                    boolean result = ctrlType.add(vehicleType);
                    if (result){
                        JOptionPane.showMessageDialog(this, "Vehicle Add Successfully...");
                    }else{
                        JOptionPane.showMessageDialog(this, "Vehicle Add Failed...");
                    }
        } catch (Exception ex) {
            Logger.getLogger(AddVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadVehicleType();
    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

    private void btnDeleteVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteVehicleMouseClicked

    }//GEN-LAST:event_btnDeleteVehicleMouseClicked

    private void vehicleTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleTypeComboBoxItemStateChanged
        String modelID = (String) vehicleTypeComboBox.getSelectedItem();
        VehicleTypeDTO v1;
        try {
            v1 = ctrlType.searchName(modelID);
            if(v1!=null){
                txtModelName.setText(v1.getModelName());
            }
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vehicleTypeComboBoxItemStateChanged

    private void vehicleBrandComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleBrandComboBoxItemStateChanged
        vehicleTypeComboBox.removeAllItems();
        String name=(String) vehicleBrandComboBox.getSelectedItem();
        try{
            VehicleBrandDTO v1=ctrlBrand.search(name);
            if(v1!=null){
                txtbrand.setText(v1.getVehicleID());
                ArrayList<VehicleTypeDTO> vehicleTypeDTO= ctrlType.searchID(v1.getVehicleID());
                for(VehicleTypeDTO vehicleTypeDTO1:vehicleTypeDTO){
                    vehicleTypeComboBox.addItem(vehicleTypeDTO1.getModelName());
                }
                loadVehicleType();
            }else{
                JOptionPane.showMessageDialog(null,"Dosen't match");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_vehicleBrandComboBoxItemStateChanged

    private void vehicleBrandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleBrandComboBoxActionPerformed

    }//GEN-LAST:event_vehicleBrandComboBoxActionPerformed

    private void txtModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNameActionPerformed
        txtReg.requestFocus();
    }//GEN-LAST:event_txtModelNameActionPerformed

    private void txtRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegActionPerformed
        txtYear.requestFocus();
    }//GEN-LAST:event_txtRegActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        txtColor.requestFocus();
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        txtSeat.requestFocus();
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatActionPerformed
        txtFuel.requestFocus();
    }//GEN-LAST:event_txtSeatActionPerformed

    private void txtFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelActionPerformed
        txtPrice.requestFocus();
    }//GEN-LAST:event_txtFuelActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        txtStatus.requestFocus();
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        btnAddVehicle.requestFocus();
    }//GEN-LAST:event_txtStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressText1;
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnUpdateVehicle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameText3;
    private javax.swing.JLabel nameText4;
    private javax.swing.JLabel nameText5;
    private javax.swing.JLabel salaryText;
    private javax.swing.JLabel salaryText1;
    private javax.swing.JLabel salaryText2;
    private javax.swing.JLabel salaryText3;
    private javax.swing.JLabel salaryText4;
    private javax.swing.JLabel salaryText5;
    private javax.swing.JLabel salaryText6;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtFuel;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtReg;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtYear;
    private javax.swing.JLabel txtbrand;
    private javax.swing.JTextField txtid;
    private javax.swing.JComboBox vehicleBrandComboBox;
    private javax.swing.JComboBox vehicleTypeComboBox;
    private javax.swing.JTable vehicleTypeTable;
    // End of variables declaration//GEN-END:variables

    private void loadVehicleBrand(){
        try{
            ArrayList<VehicleBrandDTO> vehicleBrandList = ctrlBrand.getAllBrandName();
            for(int i=0;i < vehicleBrandList.size();i++){
                VehicleBrandDTO vehicleBrand=vehicleBrandList.get(i);
                vehicleBrandComboBox.addItem(vehicleBrand.getVehicleBrandName());
            } 
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadVehicleType() {
        String brandID = (String) txtbrand.getText();
        try {
            VehicleBrandDTO vb = ctrlBrand.search(brandID);
            if(vb==null){
                ArrayList<VehicleTypeDTO> vehicleTypeList = ctrlType.nameGetAll(brandID);
                DefaultTableModel dtm = (DefaultTableModel) vehicleTypeTable.getModel();
                dtm.setRowCount(0);
                for(VehicleTypeDTO vt1 : vehicleTypeList){
                    Object[] rowData = {vt1.getModelName(),vt1.getRegNo(),vt1.getYear(),vt1.getVehicleColor(),vt1.getSeatCapacity(),vt1.getVehicleFuelType(),vt1.getPrice(),vt1.getVehicleStatus()};
                    dtm.addRow(rowData);
                }
            }else{
            }
        } catch (Exception ex) {
            Logger .getLogger(AddVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
