/*//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carrental.views;


import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.carrental.controller.ControllerFactory;
import lk.ijse.carrental.controller.custom.VehicleBrandController;
import lk.ijse.carrental.controller.custom.VehicleTypeController;
import lk.ijse.carrental.dto.VehicleBrandDTO;
import lk.ijse.carrental.dto.VehicleTypeDTO;

/**
 *
 * @author Nuwan Pradeep
 */
public class AvailableCars extends javax.swing.JFrame {
    private VehicleBrandController vehicleBrandcntrl;
    private VehicleTypeController vehicleTypecntrl;

    /**
     * Creates new form availablaCars
     */
    public AvailableCars() {
        initComponents();
       
       
        vehicleBrandcntrl = (VehicleBrandController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VEHICLEBRAND);
        vehicleTypecntrl = (VehicleTypeController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VEHICLETYPE);
     loadVehicleBrand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availableVehicle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        priceLbl = new javax.swing.JPanel();
        vehicleBrandComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vehicleTypeComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtYear = new javax.swing.JLabel();
        brandIDTxt = new javax.swing.JLabel();
        txtFuel = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSeat = new javax.swing.JLabel();
        txtRegNo1 = new javax.swing.JLabel();
        btnSelectVehicle = new javax.swing.JButton();
        a2 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        availableVehicle.setBackground(new java.awt.Color(153, 153, 153));
        availableVehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Select Vehicle ");
        availableVehicle.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        priceLbl.setBackground(new java.awt.Color(102, 102, 102));
        priceLbl.setBorder(null);
        priceLbl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehicleBrandComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        vehicleBrandComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleBrandComboBoxItemStateChanged(evt);
            }
        });
        vehicleBrandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleBrandComboBoxActionPerformed(evt);
            }
        });
        priceLbl.add(vehicleBrandComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 57, 209, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setText("Select Vehicle Brand : ");
        priceLbl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 57, 197, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("Select Vehicle Model : ");
        priceLbl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 62, 197, 30));

        vehicleTypeComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        vehicleTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleTypeComboBoxItemStateChanged(evt);
            }
        });
        priceLbl.add(vehicleTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 209, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("Vehicle Color  :");
        priceLbl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 140, 21));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("Manufacture Year  :");
        priceLbl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 163, 197, 21));

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel9.setText("RegNo.  :");
        priceLbl.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 21));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setText("Fuel Type  :");
        priceLbl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 230, 197, 21));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel11.setText("Status  :");
        priceLbl.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 301, 197, -1));

        txtColor.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 230, 251, 21));

        txtYear.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 230, 21));

        brandIDTxt.setBackground(new java.awt.Color(255, 255, 255));
        brandIDTxt.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        brandIDTxt.setForeground(new java.awt.Color(153, 204, 255));
        priceLbl.add(brandIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 30, 190, 21));

        txtFuel.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 230, 21));

        txtStatus.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 292, 270, 30));

        jLabel17.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel17.setText("Price One Day  :");
        priceLbl.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 190, -1));

        txtPrice.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        priceLbl.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 251, 21));

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel12.setText("Seat Capacity  :");
        priceLbl.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 150, 21));

        txtSeat.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 251, 21));

        txtRegNo1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtRegNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 163, 251, 21));

        btnSelectVehicle.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnSelectVehicle.setText("Select Vehicle");
        priceLbl.add(btnSelectVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, -1, -1));

        availableVehicle.add(priceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1060, 540));

        a2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        availableVehicle.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 251, 21));

        a1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        availableVehicle.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 251, 21));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(availableVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(availableVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleBrandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleBrandComboBoxActionPerformed
      
    }//GEN-LAST:event_vehicleBrandComboBoxActionPerformed

    private void vehicleBrandComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleBrandComboBoxItemStateChanged
        vehicleTypeComboBox.removeAllItems();
        String name=(String) vehicleBrandComboBox.getSelectedItem();
        try{    
            VehicleBrandDTO v1=vehicleBrandcntrl.search(name);
            if(v1!=null){ 
                brandIDTxt.setText(v1.getVehicleID());
                ArrayList<VehicleTypeDTO> vehicleTypeDTO= vehicleTypecntrl.searchID(v1.getVehicleID());
                for(VehicleTypeDTO vehicleTypeDTO1:vehicleTypeDTO){
                    vehicleTypeComboBox.addItem(vehicleTypeDTO1.getModelName());
                }
            }else{
                JOptionPane.showMessageDialog(null,"Dosen't match");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_vehicleBrandComboBoxItemStateChanged

    private void vehicleTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleTypeComboBoxItemStateChanged
        String modelID = (String) vehicleTypeComboBox.getSelectedItem();
        VehicleTypeDTO v1;
        try {
            v1 = vehicleTypecntrl.searchName(modelID);
            if(v1!=null){
                a2.setText(v1.getRegNo());
                txtColor.setText(v1.getVehicleColor());
                txtFuel.setText(v1.getVehicleFuelType());
                txtPrice.setText(Double.toString(v1.getPrice()));
                txtStatus.setText(v1.getVehicleStatus());
                txtYear.setText(Integer.toString(v1.getYear()));
                txtSeat.setText(Integer.toString(v1.getSeatCapacity()));
            }
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vehicleTypeComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvailableCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JPanel availableVehicle;
    private javax.swing.JLabel brandIDTxt;
    private javax.swing.JButton btnSelectVehicle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel priceLbl;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtFuel;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtRegNo1;
    private javax.swing.JLabel txtSeat;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtYear;
    private javax.swing.JComboBox vehicleBrandComboBox;
    private javax.swing.JComboBox vehicleTypeComboBox;
    // End of variables declaration//GEN-END:variables
    /*private void setVehicleBrandDetails() throws Exception{
    ArrayList<VehicleBrandDTO> vehicleBrandList = VehicleBrandDAOImpl.getAll();
    DefaultTableModel dtm = (DefaultTableModel) vehicleBrandTable.getModel();
    dtm.setRowCount(0);
    for(VehicleBrandDTO vb1 : vehicleBrandList){
    Object[] rowData = {vb1.getVehicleID(),vb1.getVehicleBrandName()};
    dtm.addRow(rowData);
    }
    }*/
    
    private void loadVehicleBrand(){
        try{
            ArrayList<VehicleBrandDTO> vehicleBrandList = vehicleBrandcntrl.getAllBrandName();
            for(int i=0;i < vehicleBrandList.size();i++){
                VehicleBrandDTO vehicleBrand=vehicleBrandList.get(i);
                vehicleBrandComboBox.addItem(vehicleBrand.getVehicleBrandName());
            } 
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*private void loadVehicleType(){
        try{
            ArrayList<VehicleTypeDTO> vehicleTypeList = VehicleTypeControllerImpl.getAll();
            for(int i=0;i < vehicleTypeList.size();i++){
                VehicleTypeDTO vehicleType=vehicleTypeList.get(i);
                vehicleTypeComboBox.addItem(vehicleType.getModelName());
            } 
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
}
