/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carrental.views;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import lk.ijse.carrental.IDGenerator.IDGenerator;
import lk.ijse.carrental.controller.ControllerFactory;
import lk.ijse.carrental.controller.custom.CustomerController;
import lk.ijse.carrental.controller.custom.VehicleBrandController;
import lk.ijse.carrental.controller.custom.VehicleTypeController;
import lk.ijse.carrental.dto.CustomerDTO;
import lk.ijse.carrental.dto.VehicleBrandDTO;
import lk.ijse.carrental.dto.VehicleTypeDTO;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author Nuwan Pradeep
 */
public class main extends javax.swing.JFrame {
    private VehicleBrandController vehicleBrandcntrl;
    private VehicleTypeController vehicleTypecntrl;
    private CustomerController custController;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        dateSelectPanel.setVisible(false);
        availableVehicle.setVisible(false);
        selectCustomerPanel.setVisible(false);
        BillPanel.setVisible(false);
        registerCustomerPanel1.setVisible(false);
        addCustomerPanel1.setVisible(false);
        //this.setOpacity(0.9f);
        setDate();
        setTime();
        vehicleBrandcntrl = (VehicleBrandController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VEHICLEBRAND);
        vehicleTypecntrl = (VehicleTypeController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VEHICLETYPE);
        custController = (CustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER);
        loadCustomerIDs();
        loadVehicleBrand();
        setId();
        loadBillDetails();
        
    }
    public void setId() {
        try {
            String newId = IDGenerator.getNewId("customer", "CID", "C", 2);
            idTxt.setText(newId);
            idTxt.setEditable(false);
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        carrentalPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dateLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        restoreBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        viewReserveLbl = new javax.swing.JLabel();
        reserveVehicleLbl = new javax.swing.JLabel();
        viewPaymentLbl = new javax.swing.JLabel();
        modifyCarsLbl = new javax.swing.JLabel();
        modifyReserveLbl = new javax.swing.JLabel();
        viewCarsLbl1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        dateSelectPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        businessRadioButton = new javax.swing.JRadioButton();
        leisureRadioButton = new javax.swing.JRadioButton();
        dropOffDateSelect = new org.jdesktop.swingx.JXDatePicker();
        pickUpDateSelect = new org.jdesktop.swingx.JXDatePicker();
        pickUpDateLbl = new javax.swing.JLabel();
        dropOfDateLbl = new javax.swing.JLabel();
        btnSearchVehicle = new javax.swing.JButton();
        setvalue = new javax.swing.JLabel();
        availableVehicle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        priceLbl = new javax.swing.JPanel();
        vehicleBrandComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vehicleTypeComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        txtYear = new javax.swing.JLabel();
        brandIDTxt = new javax.swing.JLabel();
        txtFuel = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSeat = new javax.swing.JLabel();
        txtRegNo1 = new javax.swing.JLabel();
        btnSelectVehicle = new javax.swing.JButton();
        a2 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        selectCustomerPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        vehicleBrandDetailsPanel = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        addCustomerPanel1 = new javax.swing.JPanel();
        addCustomerBtn1 = new javax.swing.JButton();
        nameText15 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        nameText3 = new javax.swing.JLabel();
        nameText7 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nameText8 = new javax.swing.JLabel();
        licenseText = new javax.swing.JTextField();
        NICText = new javax.swing.JTextField();
        nameText12 = new javax.swing.JLabel();
        DOBText = new javax.swing.JTextField();
        nameText11 = new javax.swing.JLabel();
        nameText4 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        nameText10 = new javax.swing.JLabel();
        tpText = new javax.swing.JTextField();
        nameText9 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        registerCustomerPanel1 = new javax.swing.JPanel();
        nextCustomerBtn = new javax.swing.JButton();
        addressText1 = new javax.swing.JTextField();
        nameText1 = new javax.swing.JTextField();
        nameText5 = new javax.swing.JLabel();
        nameText14 = new javax.swing.JLabel();
        nameText13 = new javax.swing.JLabel();
        custIDComboBox = new javax.swing.JComboBox();
        nameText6 = new javax.swing.JLabel();
        BillPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnPrintBill = new javax.swing.JButton();
        btnViewBill = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        blblCustName = new javax.swing.JLabel();
        blblPickUpDate = new javax.swing.JLabel();
        blblDropOffDate = new javax.swing.JLabel();
        blblPricePerDay = new javax.swing.JLabel();
        blblReserveDate = new javax.swing.JLabel();
        blblModelName = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carrentalPanel.setBackground(new java.awt.Color(255, 255, 255));
        carrentalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        dateLbl.setText("Date");
        jPanel2.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 110, -1));

        timeLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        timeLbl.setText("Time");
        jPanel2.add(timeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 100, -1));

        restoreBtn.setBackground(new java.awt.Color(204, 204, 255));
        restoreBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/Stop30.png"))); // NOI18N
        restoreBtn.setOpaque(true);
        jPanel2.add(restoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 30, 30));

        minimizeBtn.setBackground(new java.awt.Color(204, 204, 255));
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/Minus30.png"))); // NOI18N
        minimizeBtn.setOpaque(true);
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
        });
        jPanel2.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 30, 30));

        closeBtn.setBackground(new java.awt.Color(204, 204, 255));
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/close30.png"))); // NOI18N
        closeBtn.setOpaque(true);
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        jPanel2.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        carrentalPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        viewReserveLbl.setBackground(new java.awt.Color(51, 153, 255));
        viewReserveLbl.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        viewReserveLbl.setForeground(new java.awt.Color(0, 51, 153));
        viewReserveLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/select1 30.png"))); // NOI18N
        viewReserveLbl.setText("View Reserve Details");
        viewReserveLbl.setOpaque(true);
        viewReserveLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewReserveLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewReserveLblMouseExited(evt);
            }
        });

        reserveVehicleLbl.setBackground(new java.awt.Color(51, 153, 255));
        reserveVehicleLbl.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        reserveVehicleLbl.setForeground(new java.awt.Color(0, 51, 153));
        reserveVehicleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/select1 30.png"))); // NOI18N
        reserveVehicleLbl.setText("Resrve Vehicle");
        reserveVehicleLbl.setOpaque(true);
        reserveVehicleLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserveVehicleLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reserveVehicleLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reserveVehicleLblMouseExited(evt);
            }
        });

        viewPaymentLbl.setBackground(new java.awt.Color(51, 153, 255));
        viewPaymentLbl.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        viewPaymentLbl.setForeground(new java.awt.Color(0, 51, 153));
        viewPaymentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/select1 30.png"))); // NOI18N
        viewPaymentLbl.setText("View Payment");
        viewPaymentLbl.setOpaque(true);
        viewPaymentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPaymentLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPaymentLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewPaymentLblMouseExited(evt);
            }
        });

        modifyCarsLbl.setBackground(new java.awt.Color(51, 153, 255));
        modifyCarsLbl.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        modifyCarsLbl.setForeground(new java.awt.Color(0, 51, 153));
        modifyCarsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/select1 30.png"))); // NOI18N
        modifyCarsLbl.setText("Modify Car Details");
        modifyCarsLbl.setOpaque(true);
        modifyCarsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyCarsLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyCarsLblMouseExited(evt);
            }
        });

        modifyReserveLbl.setBackground(new java.awt.Color(51, 153, 255));
        modifyReserveLbl.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        modifyReserveLbl.setForeground(new java.awt.Color(0, 51, 153));
        modifyReserveLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/select1 30.png"))); // NOI18N
        modifyReserveLbl.setText("Modify Reservation");
        modifyReserveLbl.setOpaque(true);
        modifyReserveLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyReserveLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyReserveLblMouseExited(evt);
            }
        });

        viewCarsLbl1.setBackground(new java.awt.Color(51, 153, 255));
        viewCarsLbl1.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        viewCarsLbl1.setForeground(new java.awt.Color(0, 51, 153));
        viewCarsLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/carrental/resourse/select1 30.png"))); // NOI18N
        viewCarsLbl1.setText("View Cars");
        viewCarsLbl1.setOpaque(true);
        viewCarsLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewCarsLbl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewCarsLbl1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveVehicleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCarsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyCarsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyReserveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewReserveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPaymentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(reserveVehicleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewReserveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewPaymentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modifyCarsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modifyReserveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewCarsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );

        carrentalPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 670));

        mainPanel.setLayout(new java.awt.CardLayout());

        dateSelectPanel.setBackground(new java.awt.Color(153, 153, 153));
        dateSelectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Search for Vehicle Hire");
        dateSelectPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Drop-off Date");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setText("Pick-up Date");

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("Purpose for rental");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        businessRadioButton.setBackground(new java.awt.Color(102, 102, 102));
        businessRadioButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        businessRadioButton.setText("Business");
        jPanel8.add(businessRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        leisureRadioButton.setBackground(new java.awt.Color(102, 102, 102));
        leisureRadioButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        leisureRadioButton.setText("Leisure");
        jPanel8.add(leisureRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        dropOffDateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropOffDateSelectActionPerformed(evt);
            }
        });

        pickUpDateSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pickUpDateSelectMouseClicked(evt);
            }
        });
        pickUpDateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpDateSelectActionPerformed(evt);
            }
        });
        pickUpDateSelect.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pickUpDateSelectPropertyChange(evt);
            }
        });

        pickUpDateLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dropOfDateLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSearchVehicle.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnSearchVehicle.setText("Search Vehicle");
        btnSearchVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVehicleActionPerformed(evt);
            }
        });

        setvalue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 846, Short.MAX_VALUE)
                .addComponent(btnSearchVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel5)
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickUpDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(pickUpDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(197, 197, 197)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropOffDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dropOfDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(setvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(setvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropOffDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pickUpDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pickUpDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropOfDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnSearchVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        dateSelectPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1060, 500));

        mainPanel.add(dateSelectPanel, "card2");

        availableVehicle.setBackground(new java.awt.Color(153, 153, 153));
        availableVehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel3.setText("Select Vehicle ");
        availableVehicle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        priceLbl.setBackground(new java.awt.Color(102, 102, 102));
        priceLbl.setBorder(null);
        priceLbl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehicleBrandComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        vehicleBrandComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleBrandComboBoxItemStateChanged(evt);
            }
        });
        vehicleBrandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleBrandComboBoxActionPerformed(evt);
            }
        });
        priceLbl.add(vehicleBrandComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 57, 209, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("Select Vehicle Brand : ");
        priceLbl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 57, 197, 30));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("Select Vehicle Model : ");
        priceLbl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 62, 197, 30));

        vehicleTypeComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        vehicleTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleTypeComboBoxItemStateChanged(evt);
            }
        });
        priceLbl.add(vehicleTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 209, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("Vehicle Color  :");
        priceLbl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 140, 21));

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel9.setText("Manufacture Year  :");
        priceLbl.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 163, 197, 21));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setText("RegNo.  :");
        priceLbl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 21));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel11.setText("Fuel Type  :");
        priceLbl.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 230, 197, 21));

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel12.setText("Status  :");
        priceLbl.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 301, 197, -1));

        txtColor.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 230, 251, 21));

        txtYear.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 230, 21));

        brandIDTxt.setBackground(new java.awt.Color(255, 255, 255));
        brandIDTxt.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        brandIDTxt.setForeground(new java.awt.Color(153, 204, 255));
        priceLbl.add(brandIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 30, 190, 21));

        txtFuel.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 230, 21));

        txtStatus.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 292, 270, 30));

        jLabel17.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel17.setText("Price One Day  :");
        priceLbl.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 190, -1));

        txtPrice.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        priceLbl.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 251, 21));

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel13.setText("Seat Capacity  :");
        priceLbl.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 150, 21));

        txtSeat.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 251, 21));

        txtRegNo1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(txtRegNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 163, 251, 21));

        btnSelectVehicle.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnSelectVehicle.setText("Select Vehicle");
        btnSelectVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectVehicleActionPerformed(evt);
            }
        });
        priceLbl.add(btnSelectVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, -1, -1));

        availableVehicle.add(priceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1060, 540));

        a2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        availableVehicle.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 251, 21));

        a1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        availableVehicle.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 251, 21));

        mainPanel.add(availableVehicle, "card3");

        selectCustomerPanel.setBackground(new java.awt.Color(153, 153, 153));
        selectCustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel14.setText("Select Customer  ");
        selectCustomerPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 170, -1));

        vehicleBrandDetailsPanel.setBackground(new java.awt.Color(102, 102, 102));
        vehicleBrandDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        vehicleBrandDetailsPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 10, 460));

        addCustomerBtn1.setBackground(new java.awt.Color(51, 51, 51));
        addCustomerBtn1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addCustomerBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerBtn1.setText("Add Customer");
        addCustomerBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtn1MouseClicked(evt);
            }
        });
        addCustomerBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtn1ActionPerformed(evt);
            }
        });

        nameText15.setBackground(new java.awt.Color(102, 204, 255));
        nameText15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText15.setText("Are you not registered.. Please fill you information...");

        nameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextMouseClicked(evt);
            }
        });
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        nameText3.setBackground(new java.awt.Color(102, 204, 255));
        nameText3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText3.setText("Full Name :");

        nameText7.setBackground(new java.awt.Color(102, 204, 255));
        nameText7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText7.setText("Customer ID : ");

        idTxt.setName(""); // NOI18N
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        nameText8.setBackground(new java.awt.Color(102, 204, 255));
        nameText8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText8.setText("License no. : ");

        licenseText.setName(""); // NOI18N
        licenseText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                licenseTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                licenseTextFocusLost(evt);
            }
        });
        licenseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseTextActionPerformed(evt);
            }
        });
        licenseText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                licenseTextKeyReleased(evt);
            }
        });

        NICText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICTextActionPerformed(evt);
            }
        });
        NICText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICTextKeyReleased(evt);
            }
        });

        nameText12.setBackground(new java.awt.Color(102, 204, 255));
        nameText12.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText12.setText("NIC No. : ");

        DOBText.setName(""); // NOI18N
        DOBText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextFocusLost(evt);
            }
        });
        DOBText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTextActionPerformed(evt);
            }
        });

        nameText11.setBackground(new java.awt.Color(102, 204, 255));
        nameText11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText11.setText("Date of Birth :");

        nameText4.setBackground(new java.awt.Color(102, 204, 255));
        nameText4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText4.setText("Address :");

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });

        nameText10.setBackground(new java.awt.Color(102, 204, 255));
        nameText10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText10.setText("Tp No. :");

        tpText.setName(""); // NOI18N
        tpText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpTextFocusLost(evt);
            }
        });
        tpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTextActionPerformed(evt);
            }
        });
        tpText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpTextKeyTyped(evt);
            }
        });

        nameText9.setBackground(new java.awt.Color(102, 204, 255));
        nameText9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText9.setText("Email : ");

        emailText.setName(""); // NOI18N
        emailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFocusLost(evt);
            }
        });
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        emailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout addCustomerPanel1Layout = new javax.swing.GroupLayout(addCustomerPanel1);
        addCustomerPanel1.setLayout(addCustomerPanel1Layout);
        addCustomerPanel1Layout.setHorizontalGroup(
            addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addCustomerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(addCustomerPanel1Layout.createSequentialGroup()
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCustomerPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nameText7)
                        .addGap(28, 28, 28)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCustomerPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nameText3)
                        .addGap(52, 52, 52)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCustomerPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText8)
                            .addComponent(nameText12)
                            .addComponent(nameText11)
                            .addComponent(nameText4)
                            .addComponent(nameText10)
                            .addComponent(nameText9))
                        .addGap(20, 20, 20)
                        .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NICText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addCustomerPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameText15, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addCustomerPanel1Layout.setVerticalGroup(
            addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nameText15)
                .addGap(38, 38, 38)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText7))
                .addGap(12, 12, 12)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText3))
                .addGap(12, 12, 12)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NICText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText4))
                .addGap(18, 18, 18)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText10))
                .addGap(18, 18, 18)
                .addGroup(addCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText9))
                .addGap(28, 28, 28)
                .addComponent(addCustomerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        vehicleBrandDetailsPanel.add(addCustomerPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 480));

        jButton1.setText("Registered Customer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        vehicleBrandDetailsPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 210, -1));

        jButton2.setText("New Customer");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        vehicleBrandDetailsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 210, -1));

        nextCustomerBtn.setBackground(new java.awt.Color(51, 51, 51));
        nextCustomerBtn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        nextCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextCustomerBtn.setText("Next");
        nextCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextCustomerBtnMouseClicked(evt);
            }
        });
        nextCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCustomerBtnActionPerformed(evt);
            }
        });

        addressText1.setBackground(new java.awt.Color(153, 153, 153));
        addressText1.setForeground(new java.awt.Color(255, 255, 255));

        nameText1.setBackground(new java.awt.Color(153, 153, 153));
        nameText1.setForeground(new java.awt.Color(255, 255, 255));

        nameText5.setBackground(new java.awt.Color(102, 204, 255));
        nameText5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText5.setText("Full Name :");

        nameText14.setBackground(new java.awt.Color(102, 204, 255));
        nameText14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText14.setText("Address :");

        nameText13.setBackground(new java.awt.Color(102, 204, 255));
        nameText13.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText13.setText("Customer ID : ");

        custIDComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custIDComboBoxItemStateChanged(evt);
            }
        });

        nameText6.setBackground(new java.awt.Color(102, 204, 255));
        nameText6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText6.setText("Are you register? Please select your ID ");

        javax.swing.GroupLayout registerCustomerPanel1Layout = new javax.swing.GroupLayout(registerCustomerPanel1);
        registerCustomerPanel1.setLayout(registerCustomerPanel1Layout);
        registerCustomerPanel1Layout.setHorizontalGroup(
            registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCustomerPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText5)
                    .addComponent(nameText14)
                    .addComponent(nameText13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCustomerPanel1Layout.createSequentialGroup()
                            .addComponent(nextCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCustomerPanel1Layout.createSequentialGroup()
                            .addComponent(addressText1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)))
                    .addGroup(registerCustomerPanel1Layout.createSequentialGroup()
                        .addGroup(registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(registerCustomerPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nameText6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        registerCustomerPanel1Layout.setVerticalGroup(
            registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCustomerPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(nameText6)
                .addGap(47, 47, 47)
                .addGroup(registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText13)
                    .addComponent(custIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText5))
                .addGap(18, 18, 18)
                .addGroup(registerCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText14))
                .addGap(138, 138, 138)
                .addComponent(nextCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        vehicleBrandDetailsPanel.add(registerCustomerPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 500, 480));

        selectCustomerPanel.add(vehicleBrandDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1040, 530));

        mainPanel.add(selectCustomerPanel, "card4");

        BillPanel.setBackground(new java.awt.Color(153, 153, 153));
        BillPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel15.setText("Reservation Information");
        BillPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 260, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel16.setText("Customer Name : ");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel19.setText("Vehicle Model : ");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel20.setText("Pick up Date : ");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel21.setText("Customer Name : ");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel22.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel22.setText("Drop of Date : ");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel23.setText("Payment : ");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel24.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel24.setText("Reserve Date : ");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel25.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel25.setText("Customer Name : ");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel26.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel26.setText("Customer Name : ");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel27.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel27.setText("Customer Name : ");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel28.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel28.setText("Customer Name : ");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        btnPrintBill.setBackground(new java.awt.Color(51, 51, 51));
        btnPrintBill.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnPrintBill.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintBill.setText("Print Bill");
        jPanel6.add(btnPrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 120, -1));

        btnViewBill.setBackground(new java.awt.Color(51, 51, 51));
        btnViewBill.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnViewBill.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBill.setText("View Bill");
        btnViewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBillActionPerformed(evt);
            }
        });
        jPanel6.add(btnViewBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 520, 120, -1));

        jLabel18.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 260, 20));

        blblCustName.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        blblCustName.setText("jLabel18");
        jPanel6.add(blblCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 260, 20));

        blblPickUpDate.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        blblPickUpDate.setText("jLabel18");
        jPanel6.add(blblPickUpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 260, 20));

        blblDropOffDate.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        blblDropOffDate.setText("jLabel18");
        jPanel6.add(blblDropOffDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, 20));

        blblPricePerDay.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        blblPricePerDay.setText("jLabel18");
        jPanel6.add(blblPricePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 20));

        blblReserveDate.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        blblReserveDate.setText("jLabel18");
        jPanel6.add(blblReserveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 260, 20));

        blblModelName.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        blblModelName.setText("jLabel18");
        jPanel6.add(blblModelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 260, 20));

        jLabel35.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel35.setText("jLabel18");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 260, 20));

        jLabel36.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel36.setText("jLabel18");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 260, 20));

        jLabel37.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel37.setText("jLabel18");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 260, 20));

        jLabel38.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel38.setText("jLabel18");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 260, 20));

        jLabel39.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel39.setText("jLabel18");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 260, 20));

        BillPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1050, 560));

        mainPanel.add(BillPanel, "card5");

        carrentalPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 1150, 670));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        carrentalPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1370, 20));

        getContentPane().add(carrentalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reserveVehicleLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveVehicleLblMouseEntered
        this.reserveVehicleLbl.setBackground(new Color(51, 102, 255));
        this.reserveVehicleLbl.setForeground(Color.WHITE);
    }//GEN-LAST:event_reserveVehicleLblMouseEntered

    private void reserveVehicleLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveVehicleLblMouseExited
        this.reserveVehicleLbl.setBackground(new Color(51, 153, 255));
        this.reserveVehicleLbl.setForeground(new Color(4, 17, 152));
    }//GEN-LAST:event_reserveVehicleLblMouseExited

    private void viewReserveLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReserveLblMouseEntered
        this.viewReserveLbl.setBackground(new Color(51, 102, 255));
        this.viewReserveLbl.setForeground(Color.WHITE);
    }//GEN-LAST:event_viewReserveLblMouseEntered

    private void viewReserveLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReserveLblMouseExited
        this.viewReserveLbl.setBackground(new Color(51, 153, 255));
        this.viewReserveLbl.setForeground(new Color(4, 17, 152));
    }//GEN-LAST:event_viewReserveLblMouseExited

    private void viewPaymentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPaymentLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPaymentLblMouseClicked

    private void viewPaymentLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPaymentLblMouseEntered
        this.viewPaymentLbl.setBackground(new Color(51, 102, 255));
        this.viewPaymentLbl.setForeground(Color.WHITE);
    }//GEN-LAST:event_viewPaymentLblMouseEntered

    private void viewPaymentLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPaymentLblMouseExited
        this.viewPaymentLbl.setBackground(new Color(51, 153, 255));
        this.viewPaymentLbl.setForeground(new Color(4, 17, 152));
    }//GEN-LAST:event_viewPaymentLblMouseExited

    private void modifyReserveLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyReserveLblMouseEntered
        this.modifyReserveLbl.setBackground(new Color(51, 102, 255));
        this.modifyReserveLbl.setForeground(Color.WHITE);
    }//GEN-LAST:event_modifyReserveLblMouseEntered

    private void modifyReserveLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyReserveLblMouseExited
        this.modifyReserveLbl.setBackground(new Color(51, 153, 255));
        this.modifyReserveLbl.setForeground(new Color(4, 17, 152));
    }//GEN-LAST:event_modifyReserveLblMouseExited

    private void modifyCarsLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyCarsLblMouseEntered
        this.modifyCarsLbl.setBackground(new Color(51, 102, 255));
        this.modifyCarsLbl.setForeground(Color.WHITE);
    }//GEN-LAST:event_modifyCarsLblMouseEntered

    private void modifyCarsLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyCarsLblMouseExited
        this.modifyCarsLbl.setBackground(new Color(51, 153, 255));
        this.modifyCarsLbl.setForeground(new Color(4, 17, 152));
    }//GEN-LAST:event_modifyCarsLblMouseExited

    private void viewCarsLbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCarsLbl1MouseEntered
        this.viewCarsLbl1.setBackground(new Color(51, 102, 255));
        this.viewCarsLbl1.setForeground(Color.WHITE);
    }//GEN-LAST:event_viewCarsLbl1MouseEntered

    private void viewCarsLbl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCarsLbl1MouseExited
        this.viewCarsLbl1.setBackground(new Color(51, 153, 255));
        this.viewCarsLbl1.setForeground(new Color(4, 17, 152));
    }//GEN-LAST:event_viewCarsLbl1MouseExited

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        this.closeBtn.setBackground(Color.RED);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        this.closeBtn.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_closeBtnMouseExited

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        this.minimizeBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        this.minimizeBtn.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        int res = JOptionPane.showConfirmDialog(main.this, "Do you want to exit?");
        if(res==0){
            this.dispose();
        }
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(Frame.ICONIFIED);

    }//GEN-LAST:event_minimizeBtnMouseClicked
//=======================================================================================================================
    private void reserveVehicleLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveVehicleLblMouseClicked
        dateSelectPanel.setVisible(true);
        availableVehicle.setVisible(false);
        selectCustomerPanel.setVisible(false);
        BillPanel.setVisible(false);
    }//GEN-LAST:event_reserveVehicleLblMouseClicked

    private void dropOffDateSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropOffDateSelectActionPerformed
        Date d1=dropOffDateSelect.getDate();
        SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sf.format(d1);
        dropOfDateLbl.setText(date);
        
        //;;;;;;;;;;;;;;;;;;;;;;;;;;
    }//GEN-LAST:event_dropOffDateSelectActionPerformed

    private void pickUpDateSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pickUpDateSelectMouseClicked

    }//GEN-LAST:event_pickUpDateSelectMouseClicked

    private void pickUpDateSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpDateSelectActionPerformed
        Date d1=pickUpDateSelect.getDate();
        SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sf.format(d1);
        pickUpDateLbl.setText(date);
    }//GEN-LAST:event_pickUpDateSelectActionPerformed

    private void pickUpDateSelectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pickUpDateSelectPropertyChange
        /*Date date = pickUpDateSelect.getDate();
        DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        String a=formatDate.format(date);
        pickUpDateLbl.setText(a);*/
    }//GEN-LAST:event_pickUpDateSelectPropertyChange
//=======================================================================================================================
    private void btnSearchVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVehicleActionPerformed
        dateSelectPanel.setVisible(false);
        selectCustomerPanel.setVisible(false);
        availableVehicle.setVisible(true);
        BillPanel.setVisible(false);
    }//GEN-LAST:event_btnSearchVehicleActionPerformed

    private void vehicleBrandComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleBrandComboBoxItemStateChanged
        vehicleTypeComboBox.removeAllItems();
        String name=(String) vehicleBrandComboBox.getSelectedItem();
        try{
            VehicleBrandDTO v1=vehicleBrandcntrl.search(name);
            if(v1!=null){
                brandIDTxt.setText(v1.getVehicleID());
                ArrayList<VehicleTypeDTO> vehicleTypeDTO= vehicleTypecntrl.searchID(v1.getVehicleID());
                for(VehicleTypeDTO vehicleTypeDTO1:vehicleTypeDTO){
                    vehicleTypeComboBox.addItem(vehicleTypeDTO1.getModelName());
                }
            }else{
                JOptionPane.showMessageDialog(null,"Dosen't match");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_vehicleBrandComboBoxItemStateChanged

    private void vehicleBrandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleBrandComboBoxActionPerformed

    }//GEN-LAST:event_vehicleBrandComboBoxActionPerformed

    private void vehicleTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleTypeComboBoxItemStateChanged
        String modelID = (String) vehicleTypeComboBox.getSelectedItem();
        VehicleTypeDTO v1;
        try {
            v1 = vehicleTypecntrl.searchName(modelID);
            if(v1!=null){
                a2.setText(v1.getRegNo());
                txtColor.setText(v1.getVehicleColor());
                txtFuel.setText(v1.getVehicleFuelType());
                txtPrice.setText(Double.toString(v1.getPrice()));
                txtStatus.setText(v1.getVehicleStatus());
                txtYear.setText(Integer.toString(v1.getYear()));
                txtSeat.setText(Integer.toString(v1.getSeatCapacity()));
            }
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vehicleTypeComboBoxItemStateChanged

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void nameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextMouseClicked

    }//GEN-LAST:event_nameTextMouseClicked

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        /*String name = nameText.getText().trim();
        if(name.matches("[A-Z. a-z]")){

        }else{
            JOptionPane.showMessageDialog(this, "Name is incorrect");
            nameText.requestFocusInWindow();
        }*/
        licenseText.requestFocus();
    }//GEN-LAST:event_nameTextActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        /*String name = nameText.getText().trim();
        if(name.matches("[A-Z. a-z]")){
        
        }else{
        JOptionPane.showMessageDialog(this, "Name is incorrect");
        nameText.requestFocusInWindow();
        }*/
    }//GEN-LAST:event_nameTextKeyReleased

    private void licenseTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseTextFocusGained
        //licenseText.paint(null);
    }//GEN-LAST:event_licenseTextFocusGained

    private void licenseTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseTextFocusLost

    private void licenseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseTextActionPerformed
        String license = licenseText.getText();
        if(license.matches("^[B][0-9]{1,7}$")){

        }else{
            JOptionPane.showMessageDialog(this, "License number is incorrect");
            licenseText.requestFocusInWindow();
            //licenseText.setText("");
        }
        NICText.requestFocus();
    }//GEN-LAST:event_licenseTextActionPerformed

    private void licenseTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_licenseTextKeyReleased
        /*String license = licenseText.getText();
        if(license.matches("^[B][0-9]{1,7}$")){
        
        }else{
        JOptionPane.showMessageDialog(this, "License number is incorrect");
        licenseText.requestFocusInWindow();
        //licenseText.setText("");
        }*/
    }//GEN-LAST:event_licenseTextKeyReleased

    private void NICTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICTextActionPerformed
        String nic = NICText.getText();
        if(nic.matches("^[0-9]{1,9}[VvXx]$")){

        }else{
            JOptionPane.showMessageDialog(this, "NIC number is incorrect");
            NICText.requestFocusInWindow();
            //NICText.setText("");
        }
        DOBText.requestFocus();
    }//GEN-LAST:event_NICTextActionPerformed

    private void NICTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICTextKeyReleased
        /*String nic = NICText.getText();
        if(nic.matches("^[0-9]{1,9}[VvXx]$")){
        
        }else{
        JOptionPane.showMessageDialog(this, "NIC number is incorrect");
        NICText.requestFocusInWindow();
        //NICText.setText("");
        }*/
    }//GEN-LAST:event_NICTextKeyReleased

    private void DOBTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextFocusGained

    private void DOBTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextFocusLost

    private void DOBTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTextActionPerformed
        addressText.requestFocus();
    }//GEN-LAST:event_DOBTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        tpText.requestFocus();
    }//GEN-LAST:event_addressTextActionPerformed

    private void tpTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tpTextFocusGained

    private void tpTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tpTextFocusLost

    private void tpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTextActionPerformed
        String tel = tpText.getText().trim();
        if(tel.matches("^\\d{3}\\d{7}$")){
            DOBText.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "Telephone number is incorrect");
            tpText.requestFocusInWindow();
            //tpText.selectAll();
        }
        emailText.requestFocus();
    }//GEN-LAST:event_tpTextActionPerformed

    private void tpTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpTextKeyReleased
        /*String tel = tpText.getText().trim();
        if(tel.matches("^\\d{3}\\d{7}$")){
        DOBText.requestFocus();
        }else{
        JOptionPane.showMessageDialog(this, "Telephone number is incorrect");
        tpText.requestFocusInWindow();
        //tpText.selectAll();
        }*/
    }//GEN-LAST:event_tpTextKeyReleased

    private void tpTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpTextKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||(c == KeyEvent.VK_BACK_SPACE) ||(c == KeyEvent.VK_DELETE)||(c == KeyEvent.VK_ENTER))|tpText.getText().length()>=10) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tpTextKeyTyped

    private void emailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFocusGained

    private void emailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFocusLost

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        String email = emailText.getText();
        if(email.matches("^[A-Za-z0-9]+.*[A-Za-z0-9]+@[A-Za-z0-9]+[A-Za-z0-9].+[A-Za-z0-9].$")){

        }else{
            JOptionPane.showMessageDialog(this, "Email address is incorrect");
            emailText.requestFocusInWindow();
            //emailText.setText("");
        }
        nextCustomerBtn.requestFocus();
    }//GEN-LAST:event_emailTextActionPerformed

    private void emailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyReleased
        /*String email = emailText.getText();
        if(email.matches("^[A-Za-z0-9]+.*[A-Za-z0-9]+@[A-Za-z0-9]+[A-Za-z0-9].+[A-Za-z0-9].$")){
        
        }else{
        JOptionPane.showMessageDialog(this, "Email address is incorrect");
        emailText.requestFocusInWindow();
        //emailText.setText("");
        }*/
    }//GEN-LAST:event_emailTextKeyReleased

    private void emailTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')||(c >= 'A') && (c <= 'Z') ||(c >= 'a') && (c <= 'z') ||(c =='@')||(c =='.')||(c == KeyEvent.VK_BACK_SPACE) ||(c == KeyEvent.VK_DELETE)||(c == KeyEvent.VK_ENTER))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_emailTextKeyTyped

    private void nextCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextCustomerBtnMouseClicked

    }//GEN-LAST:event_nextCustomerBtnMouseClicked

    private void nextCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCustomerBtnActionPerformed
        String name = nameText1.getText();
        String address = addressText1.getText();
        BillPanel.setVisible(true);
        selectCustomerPanel.setVisible(false);
    }//GEN-LAST:event_nextCustomerBtnActionPerformed
//=======================================================================================================================
    private void btnSelectVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectVehicleActionPerformed
        selectCustomerPanel.setVisible(true);
        dateSelectPanel.setVisible(false);
        availableVehicle.setVisible(false);
        BillPanel.setVisible(false);
    }//GEN-LAST:event_btnSelectVehicleActionPerformed

    private void custIDComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custIDComboBoxItemStateChanged
        String CID = (String) custIDComboBox.getSelectedItem();
        CustomerDTO c1;
        try {
            c1 = custController.searchName(CID);
            if(c1!=null){
                
                nameText1.setText(c1.getName());
                addressText1.setText(c1.getAddress());
            }
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_custIDComboBoxItemStateChanged

    private void addCustomerBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtn1MouseClicked

    private void addCustomerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtn1ActionPerformed
        CustomerDTO customer;
        customer = new CustomerDTO(
                idTxt.getText(),
                nameText.getText(),
                licenseText.getText(),
                NICText.getText(),
                DOBText.getText(),
                addressText.getText(),
                Integer.parseInt(tpText.getText()),
                emailText.getText());

        try {
            CustomerDTO customer1 = custController.search(idTxt.getText());
            if(customer1==null){
                try {
                    boolean result = custController.add(customer);
                    if (result){
                        JOptionPane.showMessageDialog(this, "Customer has been successfully added...Please select next button...");
                        loadCustomerIDs();
                        nameText6.setText("Registered successfully...Please select your id...");
                        registerCustomerPanel1.setVisible(true);
                        addCustomerPanel1.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(this, "Customer has not been added...");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "duplicate entry...");
            }
        } catch (Exception ex) {
            Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addCustomerBtn1ActionPerformed

    private void btnViewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBillActionPerformed
        /*try {
            JasperReport compiledReport = JasperCompileManager.compileReport(StartUp.class.getResourceAsStream("/lk/ijse/carrental/reports/ReserveVehicle.jrxml"));
            HashMap<String,Object> parameters = new HashMap<>();
            parameters.put("studentName", txtStudentName.getText());
            parameters.put("studentAge", Integer.parseInt(txtAge.getText()));
            JasperPrint filledReport = JasperFillManager.fillReport(compiledReport,parameters , new JREmptyDataSource());
            JasperReportViewer frmViewer = new JasperReportViewer(filledReport);
            frmViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnViewBillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        addCustomerPanel1.setVisible(true);
        registerCustomerPanel1.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        registerCustomerPanel1.setVisible(true);
        addCustomerPanel1.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BillPanel;
    private javax.swing.JTextField DOBText;
    private javax.swing.JTextField NICText;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JButton addCustomerBtn1;
    private javax.swing.JPanel addCustomerPanel1;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField addressText1;
    private javax.swing.JPanel availableVehicle;
    private javax.swing.JLabel blblCustName;
    private javax.swing.JLabel blblDropOffDate;
    private javax.swing.JLabel blblModelName;
    private javax.swing.JLabel blblPickUpDate;
    private javax.swing.JLabel blblPricePerDay;
    private javax.swing.JLabel blblReserveDate;
    private javax.swing.JLabel brandIDTxt;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JButton btnSearchVehicle;
    private javax.swing.JButton btnSelectVehicle;
    private javax.swing.JButton btnViewBill;
    private javax.swing.JRadioButton businessRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel carrentalPanel;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JComboBox custIDComboBox;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JPanel dateSelectPanel;
    private javax.swing.JLabel dropOfDateLbl;
    private org.jdesktop.swingx.JXDatePicker dropOffDateSelect;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JRadioButton leisureRadioButton;
    private javax.swing.JTextField licenseText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel modifyCarsLbl;
    private javax.swing.JLabel modifyReserveLbl;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nameText1;
    private javax.swing.JLabel nameText10;
    private javax.swing.JLabel nameText11;
    private javax.swing.JLabel nameText12;
    private javax.swing.JLabel nameText13;
    private javax.swing.JLabel nameText14;
    private javax.swing.JLabel nameText15;
    private javax.swing.JLabel nameText3;
    private javax.swing.JLabel nameText4;
    private javax.swing.JLabel nameText5;
    private javax.swing.JLabel nameText6;
    private javax.swing.JLabel nameText7;
    private javax.swing.JLabel nameText8;
    private javax.swing.JLabel nameText9;
    private javax.swing.JButton nextCustomerBtn;
    private javax.swing.JLabel pickUpDateLbl;
    private org.jdesktop.swingx.JXDatePicker pickUpDateSelect;
    private javax.swing.JPanel priceLbl;
    private javax.swing.JPanel registerCustomerPanel1;
    private javax.swing.JLabel reserveVehicleLbl;
    private javax.swing.JLabel restoreBtn;
    private javax.swing.JPanel selectCustomerPanel;
    private javax.swing.JLabel setvalue;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JTextField tpText;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtFuel;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtRegNo1;
    private javax.swing.JLabel txtSeat;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtYear;
    private javax.swing.JComboBox vehicleBrandComboBox;
    private javax.swing.JPanel vehicleBrandDetailsPanel;
    private javax.swing.JComboBox vehicleTypeComboBox;
    private javax.swing.JLabel viewCarsLbl1;
    private javax.swing.JLabel viewPaymentLbl;
    private javax.swing.JLabel viewReserveLbl;
    // End of variables declaration//GEN-END:variables
private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        dateLbl.setText(s.format(d));
    }

    private void setTime() {
        new Timer(0, (ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
            timeLbl.setText(s.format(d));
        }).start();
    }
    private void loadVehicleBrand(){
        try{
            ArrayList<VehicleBrandDTO> vehicleBrandList = vehicleBrandcntrl.getAllBrandName();
            for(int i=0;i < vehicleBrandList.size();i++){
                VehicleBrandDTO vehicleBrand=vehicleBrandList.get(i);
                vehicleBrandComboBox.addItem(vehicleBrand.getVehicleBrandName());
            } 
        } catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadCustomerIDs(){
        try{
            ArrayList<CustomerDTO> customerList = custController.getAllIDs();
            for(int i=0;i < customerList.size();i++){
                CustomerDTO customer = customerList.get(i);
                custIDComboBox.addItem(customer.getCID());
            }
        }catch (Exception ex) {
            Logger.getLogger(AvailableCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadBillDetails() {
        blblPickUpDate.setText(pickUpDateLbl.getText());
        blblDropOffDate.setText(dropOfDateLbl.getText());
        blblCustName.setText(null);
    }
}
