/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carrental.views;

import lk.ijse.carrental.dto.CustomerDTO;

/**
 *
 * @author Nuwan Pradeep
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        checkPanel.setVisible(false);
        cardPanel.setVisible(false);
        cashPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        vehicleBrandDetailsPanel = new javax.swing.JPanel();
        nameText7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        cmbPayment = new javax.swing.JComboBox();
        cardPanel = new javax.swing.JPanel();
        txtCardNumber = new javax.swing.JTextField();
        txtCardOwnerName = new javax.swing.JTextField();
        nameText11 = new javax.swing.JLabel();
        nameText20 = new javax.swing.JLabel();
        nameText21 = new javax.swing.JLabel();
        txtCardCVVNumber = new javax.swing.JTextField();
        nameText22 = new javax.swing.JLabel();
        txtCardExpireDate = new javax.swing.JTextField();
        checkPanel = new javax.swing.JPanel();
        txtCheckNumber = new javax.swing.JTextField();
        txtCheckOwnerName = new javax.swing.JTextField();
        nameText12 = new javax.swing.JLabel();
        nameText23 = new javax.swing.JLabel();
        nameText24 = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        nameText25 = new javax.swing.JLabel();
        txtCheckExpireDate = new javax.swing.JTextField();
        cashPanel = new javax.swing.JPanel();
        txtCashPrice = new javax.swing.JTextField();
        nameText13 = new javax.swing.JLabel();
        nameText14 = new javax.swing.JLabel();
        nameText15 = new javax.swing.JLabel();
        txtCardOwnerName1 = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        addCustomerBtn2 = new javax.swing.JButton();
        addCustomerBtn1 = new javax.swing.JButton();
        addCustomerBtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(153, 153, 153));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Payment ");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 90, -1));

        vehicleBrandDetailsPanel.setBackground(new java.awt.Color(102, 102, 102));
        vehicleBrandDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameText7.setBackground(new java.awt.Color(102, 204, 255));
        nameText7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText7.setForeground(new java.awt.Color(255, 255, 255));
        nameText7.setText("Please select your payment method : ");
        vehicleBrandDetailsPanel.add(nameText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel17.setText("Full Price :");
        vehicleBrandDetailsPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 160, -1));

        txtPrice.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vehicleBrandDetailsPanel.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 251, 21));

        cmbPayment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card", "Check", " " }));
        cmbPayment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaymentItemStateChanged(evt);
            }
        });
        cmbPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaymentActionPerformed(evt);
            }
        });
        vehicleBrandDetailsPanel.add(cmbPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 160, -1));

        cardPanel.setBackground(new java.awt.Color(102, 102, 102));

        txtCardOwnerName.setName(""); // NOI18N
        txtCardOwnerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCardOwnerNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCardOwnerNameFocusLost(evt);
            }
        });

        nameText11.setBackground(new java.awt.Color(102, 204, 255));
        nameText11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText11.setForeground(new java.awt.Color(255, 255, 255));
        nameText11.setText("Owner Name :");

        nameText20.setBackground(new java.awt.Color(102, 204, 255));
        nameText20.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText20.setForeground(new java.awt.Color(255, 255, 255));
        nameText20.setText("Card Number : ");

        nameText21.setBackground(new java.awt.Color(102, 204, 255));
        nameText21.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText21.setForeground(new java.awt.Color(255, 255, 255));
        nameText21.setText("CVV Number : ");

        nameText22.setBackground(new java.awt.Color(102, 204, 255));
        nameText22.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText22.setForeground(new java.awt.Color(255, 255, 255));
        nameText22.setText("Expire Date : ");

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText11)
                    .addComponent(nameText22)
                    .addComponent(nameText21)
                    .addComponent(nameText20))
                .addGap(97, 97, 97)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCardExpireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCardCVVNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCardOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText20))
                .addGap(12, 12, 12)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardCVVNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardExpireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText22))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        vehicleBrandDetailsPanel.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        checkPanel.setBackground(new java.awt.Color(102, 102, 102));

        txtCheckOwnerName.setName(""); // NOI18N
        txtCheckOwnerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCheckOwnerNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCheckOwnerNameFocusLost(evt);
            }
        });

        nameText12.setBackground(new java.awt.Color(102, 204, 255));
        nameText12.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText12.setForeground(new java.awt.Color(255, 255, 255));
        nameText12.setText("Owner Name :");

        nameText23.setBackground(new java.awt.Color(102, 204, 255));
        nameText23.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText23.setForeground(new java.awt.Color(255, 255, 255));
        nameText23.setText("Check Number : ");

        nameText24.setBackground(new java.awt.Color(102, 204, 255));
        nameText24.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText24.setForeground(new java.awt.Color(255, 255, 255));
        nameText24.setText("Bank Name : ");

        nameText25.setBackground(new java.awt.Color(102, 204, 255));
        nameText25.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText25.setForeground(new java.awt.Color(255, 255, 255));
        nameText25.setText("Expire Date : ");

        javax.swing.GroupLayout checkPanelLayout = new javax.swing.GroupLayout(checkPanel);
        checkPanel.setLayout(checkPanelLayout);
        checkPanelLayout.setHorizontalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText12)
                    .addComponent(nameText25)
                    .addComponent(nameText24)
                    .addComponent(nameText23))
                .addGap(97, 97, 97)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCheckExpireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCheckNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCheckOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        checkPanelLayout.setVerticalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText23))
                .addGap(12, 12, 12)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckExpireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText25))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        vehicleBrandDetailsPanel.add(checkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        cashPanel.setBackground(new java.awt.Color(102, 102, 102));

        txtCashPrice.setName(""); // NOI18N
        txtCashPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCashPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCashPriceFocusLost(evt);
            }
        });

        nameText13.setBackground(new java.awt.Color(102, 204, 255));
        nameText13.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText13.setForeground(new java.awt.Color(255, 255, 255));
        nameText13.setText("Price  :");

        nameText14.setBackground(new java.awt.Color(102, 204, 255));
        nameText14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText14.setForeground(new java.awt.Color(255, 255, 255));
        nameText14.setText("Rs.");

        javax.swing.GroupLayout cashPanelLayout = new javax.swing.GroupLayout(cashPanel);
        cashPanel.setLayout(cashPanelLayout);
        cashPanelLayout.setHorizontalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashPanelLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(nameText13)
                .addGap(110, 110, 110)
                .addComponent(nameText14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCashPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        cashPanelLayout.setVerticalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCashPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText13)
                    .addComponent(nameText14))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        vehicleBrandDetailsPanel.add(cashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        nameText15.setBackground(new java.awt.Color(102, 204, 255));
        nameText15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        nameText15.setForeground(new java.awt.Color(255, 255, 255));
        nameText15.setText("Offer Details :");
        vehicleBrandDetailsPanel.add(nameText15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        txtCardOwnerName1.setName(""); // NOI18N
        txtCardOwnerName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCardOwnerName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCardOwnerName1FocusLost(evt);
            }
        });
        vehicleBrandDetailsPanel.add(txtCardOwnerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 290, -1));

        btnConfirm.setBackground(new java.awt.Color(51, 102, 255));
        btnConfirm.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm");
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
        });
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        vehicleBrandDetailsPanel.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 110, 20));

        mainPanel.add(vehicleBrandDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1040, 530));

        addCustomerBtn2.setBackground(new java.awt.Color(51, 102, 255));
        addCustomerBtn2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addCustomerBtn2.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerBtn2.setText("Next");
        addCustomerBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtn2MouseClicked(evt);
            }
        });
        addCustomerBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtn2ActionPerformed(evt);
            }
        });
        mainPanel.add(addCustomerBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 150, 30));

        addCustomerBtn1.setBackground(new java.awt.Color(51, 102, 255));
        addCustomerBtn1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addCustomerBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerBtn1.setText("Print Bill");
        addCustomerBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtn1MouseClicked(evt);
            }
        });
        addCustomerBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtn1ActionPerformed(evt);
            }
        });
        mainPanel.add(addCustomerBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 150, 30));

        addCustomerBtn3.setBackground(new java.awt.Color(51, 102, 255));
        addCustomerBtn3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addCustomerBtn3.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerBtn3.setText("View Bill");
        addCustomerBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtn3MouseClicked(evt);
            }
        });
        addCustomerBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtn3ActionPerformed(evt);
            }
        });
        mainPanel.add(addCustomerBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
        
    }//GEN-LAST:event_btnConfirmMouseClicked

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtCardOwnerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardOwnerNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardOwnerNameFocusLost

    private void txtCardOwnerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardOwnerNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardOwnerNameFocusGained

    private void txtCheckOwnerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckOwnerNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOwnerNameFocusGained

    private void txtCheckOwnerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckOwnerNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOwnerNameFocusLost

    private void cmbPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentActionPerformed
        String cmb = (String) cmbPayment.getSelectedItem();
        if(cmb == "Credit Card"){
            cardPanel.setVisible(true);
            checkPanel.setVisible(false);
            cashPanel.setVisible(false);
        }else if(cmb == "Check"){
            cardPanel.setVisible(false);
            checkPanel.setVisible(true);
            cashPanel.setVisible(false);
        }else if(cmb == "Cash"){
            cardPanel.setVisible(false);
            checkPanel.setVisible(false);
            cashPanel.setVisible(true);
        }
    }//GEN-LAST:event_cmbPaymentActionPerformed

    private void cmbPaymentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaymentItemStateChanged
        
    }//GEN-LAST:event_cmbPaymentItemStateChanged

    private void txtCashPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashPriceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashPriceFocusGained

    private void txtCashPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashPriceFocusLost

    private void txtCardOwnerName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardOwnerName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardOwnerName1FocusGained

    private void txtCardOwnerName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardOwnerName1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardOwnerName1FocusLost

    private void addCustomerBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtn2MouseClicked

    private void addCustomerBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtn2ActionPerformed

    private void addCustomerBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtn1MouseClicked

    private void addCustomerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtn1ActionPerformed

    private void addCustomerBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtn3MouseClicked

    private void addCustomerBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn1;
    private javax.swing.JButton addCustomerBtn2;
    private javax.swing.JButton addCustomerBtn3;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel cashPanel;
    private javax.swing.JPanel checkPanel;
    private javax.swing.JComboBox cmbPayment;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameText11;
    private javax.swing.JLabel nameText12;
    private javax.swing.JLabel nameText13;
    private javax.swing.JLabel nameText14;
    private javax.swing.JLabel nameText15;
    private javax.swing.JLabel nameText20;
    private javax.swing.JLabel nameText21;
    private javax.swing.JLabel nameText22;
    private javax.swing.JLabel nameText23;
    private javax.swing.JLabel nameText24;
    private javax.swing.JLabel nameText25;
    private javax.swing.JLabel nameText7;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtCardCVVNumber;
    private javax.swing.JTextField txtCardExpireDate;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCardOwnerName;
    private javax.swing.JTextField txtCardOwnerName1;
    private javax.swing.JTextField txtCashPrice;
    private javax.swing.JTextField txtCheckExpireDate;
    private javax.swing.JTextField txtCheckNumber;
    private javax.swing.JTextField txtCheckOwnerName;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JPanel vehicleBrandDetailsPanel;
    // End of variables declaration//GEN-END:variables
}
