/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carrental.views;

/**
 *
 * @author Nuwan Pradeep
 */
public class registeredCustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form registeredCustomerForm
     */
    public registeredCustomerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        priceLbl = new javax.swing.JPanel();
        vehicleBrandComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vehicleTypeComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        colorLbl = new javax.swing.JLabel();
        yearLbl = new javax.swing.JLabel();
        regNoLbl = new javax.swing.JLabel();
        FuelLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Select Vehicle ");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        priceLbl.setBackground(new java.awt.Color(102, 102, 102));
        priceLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        priceLbl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehicleBrandComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(vehicleBrandComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 209, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setText("Select Vehicle Brand : ");
        priceLbl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 197, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("Select Vehicle Type : ");
        priceLbl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 197, -1));

        vehicleTypeComboBox.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(vehicleTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 209, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("Vehicle Color  :");
        priceLbl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 140, 21));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("Manufacture Year  :");
        priceLbl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 197, 21));

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel9.setText("RegNo.  :");
        priceLbl.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, 21));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setText("Fuel Type  :");
        priceLbl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 197, 21));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel11.setText("Status  :");
        priceLbl.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 197, -1));

        colorLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(colorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 251, 21));

        yearLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(yearLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 230, 21));

        regNoLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(regNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 251, 21));

        FuelLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(FuelLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 230, 21));

        statusLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(statusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 219, 100));

        jLabel17.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel17.setText("Price One Day  :");
        priceLbl.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 130, -1));

        jLabel18.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        priceLbl.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 251, 21));

        jPanel6.add(priceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1060, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registeredCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registeredCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registeredCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registeredCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registeredCustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FuelLbl;
    private javax.swing.JLabel colorLbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel priceLbl;
    private javax.swing.JLabel regNoLbl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JComboBox vehicleBrandComboBox;
    private javax.swing.JComboBox vehicleTypeComboBox;
    private javax.swing.JLabel yearLbl;
    // End of variables declaration//GEN-END:variables
}
