/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.carrental.views;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Nuwan Pradeep
 */
public class selectDate extends javax.swing.JFrame {

    /**
     * Creates new form selectDate
     */
    public selectDate() {
        initComponents();
        dateSelect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dateSelectPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        businessRadioButton = new javax.swing.JRadioButton();
        leisureRadioButton = new javax.swing.JRadioButton();
        dropOffDateSelect = new org.jdesktop.swingx.JXDatePicker();
        pickUpDateSelect = new org.jdesktop.swingx.JXDatePicker();
        pickUpDateLbl = new javax.swing.JLabel();
        dropOfDateLbl = new javax.swing.JLabel();
        SearchVehicleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        dateSelectPanel.setBackground(new java.awt.Color(153, 153, 153));
        dateSelectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Search for Vehicle Hire");
        dateSelectPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Drop-off Date");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setText("Pick-up Date");

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("Purpose for rental");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        businessRadioButton.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(businessRadioButton);
        businessRadioButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        businessRadioButton.setText("Business");
        jPanel8.add(businessRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        leisureRadioButton.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(leisureRadioButton);
        leisureRadioButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        leisureRadioButton.setText("Leisure");
        jPanel8.add(leisureRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        dropOffDateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropOffDateSelectActionPerformed(evt);
            }
        });

        pickUpDateSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pickUpDateSelectMouseClicked(evt);
            }
        });
        pickUpDateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpDateSelectActionPerformed(evt);
            }
        });
        pickUpDateSelect.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pickUpDateSelectPropertyChange(evt);
            }
        });

        pickUpDateLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dropOfDateLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel5)
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickUpDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickUpDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(184, 184, 184)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropOfDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropOffDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(pickUpDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dropOffDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickUpDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropOfDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dateSelectPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1060, 500));

        SearchVehicleBtn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        SearchVehicleBtn.setText("Search Vehicle");
        dateSelectPanel.add(SearchVehicleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dateSelectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dateSelectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pickUpDateSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpDateSelectActionPerformed
       Date d1=pickUpDateSelect.getDate();
       SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
       String date=sf.format(d1);
       pickUpDateLbl.setText(date);
    }//GEN-LAST:event_pickUpDateSelectActionPerformed

    private void pickUpDateSelectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pickUpDateSelectPropertyChange
        /*Date date = pickUpDateSelect.getDate();
        DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        String a=formatDate.format(date);
        pickUpDateLbl.setText(a);*/
    }//GEN-LAST:event_pickUpDateSelectPropertyChange

    private void pickUpDateSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pickUpDateSelectMouseClicked
        
    }//GEN-LAST:event_pickUpDateSelectMouseClicked

    private void dropOffDateSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropOffDateSelectActionPerformed
        Date d1=dropOffDateSelect.getDate();
        SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sf.format(d1);
        dropOfDateLbl.setText(date);
    }//GEN-LAST:event_dropOffDateSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectDate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchVehicleBtn;
    private javax.swing.JRadioButton businessRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel dateSelectPanel;
    private javax.swing.JLabel dropOfDateLbl;
    private org.jdesktop.swingx.JXDatePicker dropOffDateSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton leisureRadioButton;
    private javax.swing.JLabel pickUpDateLbl;
    private org.jdesktop.swingx.JXDatePicker pickUpDateSelect;
    // End of variables declaration//GEN-END:variables

    private void dateSelect() {
        JXDatePicker picker = new JXDatePicker();
        Calendar calendar = picker.getMonthView().getCalendar();
        calendar.setTime(new Date());
        picker.getMonthView().setUpperBound(calendar.getTime());
      
    }
}
